### ISSUE TITLE
Examples for image sequence/video

### ISSUE THREAD

**Issue by tcapelle** [lucidrains/axial-attention#1]
Hello,
Do you have examples of integrating this on image sequences?
I am trying to get rid of ConvLSTM's for encoding sequence of images and AxialAttention may be a good starting point.
Do you have an exmaple/notebook that I could look to integrate this on my type of data?
Thank you for this amazing work.
Thomas

**Comment by lucidrains** [comment]
@tcapelle Hello Thomas! I have an example for video, which is images in a sequence, in the readme!
