### ISSUE TITLE
Reimplementation of image modeling results in AXIAL ATTENTION IN MULTIDIMENSIONAL TRANSFORMERS.

### ISSUE THREAD

**Issue by liujiaheng** [lucidrains/axial-attention#3]
Hi, 
this is a nice paper.
How can I use your shared code to reimplement the image modeling task on ImageNet 32x32?

Thanks.
Looking forward to your reply.

**Comment by liujiaheng** [comment]
![image](https://user-images.githubusercontent.com/27964642/100425195-b9481200-30c9-11eb-8d98-e16f3391d32e.png)
In other words,
the process is shown in the above image.
But I have not find the MaskedTransformerBlock in your code.
Could you give me some advice?

Thanks.

**Comment by lucidrains** [comment]
@liujiaheng Hi Jiaheng! I don't offer the code for the autoregressive scheme with all the clever masking. Most of my use cases for axial attention have been for enabling attention of large images without incurring the quadratic cost

**Comment by liujiaheng** [comment]
Thanks for your kind reply. I will try my best to reimplement the autoregressive scheme.
