### ISSUE TITLE
Axial-deeplab

### ISSUE THREAD

**Issue by sahilrider** [lucidrains/axial-attention#6]
Hello, Is it possible to build axial-deeplab with help of the provided axial-attention blocks? Any suggestion on how to do so?

**Comment by lucidrains** [comment]
@sahilrider Hi Sahil! Axial deeplab is a bit different - it incorporates relative positional encoding. I believe there's already a pytorch repository out there for it

**Comment by sahilrider** [comment]
Yes, right its positional encoding is different. The code repo is available but it's only for Axial-ResNet. I wanted to extend it to axial-deeplab by implementing a decoder network.

Thanks for the clarification.
